kind: Deployment
apiVersion: apps/v1
metadata:
  name: stateful-example-app-1
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/stateful-example-app-1
  uid: 96c443a6-2d8f-4f6c-b84c-eb8c3c3ded4f
  resourceVersion: '305002'
  generation: 1
  creationTimestamp: '2020-06-03T13:13:49Z'
  annotations:
    deployment.kubernetes.io/revision: '1'
  ownerReferences:
    - apiVersion: siddhi.io/v1alpha2
      kind: SiddhiProcess
      name: stateful-example-app
      uid: 6c692f14-f00d-4caf-93d9-084d20bf1ed2
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: siddhi-operator
      operation: Update
      apiVersion: apps/v1
      time: '2020-06-03T13:13:49Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:ownerReferences':
            .: {}
            'k:{"uid":"6c692f14-f00d-4caf-93d9-084d20bf1ed2"}':
              .: {}
              'f:apiVersion': {}
              'f:blockOwnerDeletion': {}
              'f:controller': {}
              'f:kind': {}
              'f:name': {}
              'f:uid': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector':
            'f:matchLabels':
              .: {}
              'f:siddhi.io/instance': {}
              'f:siddhi.io/name': {}
              'f:siddhi.io/part-of': {}
              'f:siddhi.io/version': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:siddhi.io/instance': {}
                'f:siddhi.io/name': {}
                'f:siddhi.io/part-of': {}
                'f:siddhi.io/version': {}
            'f:spec':
              'f:containers':
                'k:{"name":"siddhi-runner-runtime"}':
                  .: {}
                  'f:args': {}
                  'f:command': {}
                  'f:env':
                    .: {}
                    'k:{"name":"RECEIVER_URL"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:livenessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":9090,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                  'f:readinessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:resources': {}
                  'f:securityContext':
                    .: {}
                    'f:runAsUser': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/home/siddhi_user/siddhi-runner/siddhi-files/"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/home/siddhi_user/siddhi-runner/tmp/configs/"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/home/siddhi_user/siddhi-runner/wso2/runner/siddhi-app-persistence"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes':
                .: {}
                'k:{"name":"stateful-example-app-1-depyml"}':
                  .: {}
                  'f:configMap':
                    .: {}
                    'f:defaultMode': {}
                    'f:name': {}
                  'f:name': {}
                'k:{"name":"stateful-example-app-1-pvc"}':
                  .: {}
                  'f:name': {}
                  'f:persistentVolumeClaim':
                    .: {}
                    'f:claimName': {}
                'k:{"name":"stateful-example-app-10"}':
                  .: {}
                  'f:configMap':
                    .: {}
                    'f:defaultMode': {}
                    'f:name': {}
                  'f:name': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2020-06-03T13:14:05Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
spec:
  replicas: 1
  selector:
    matchLabels:
      siddhi.io/instance: stateful-example-app-1
      siddhi.io/name: SiddhiProcess
      siddhi.io/part-of: siddhi-operator
      siddhi.io/version: 0.2.2
  template:
    metadata:
      creationTimestamp: null
      labels:
        siddhi.io/instance: stateful-example-app-1
        siddhi.io/name: SiddhiProcess
        siddhi.io/part-of: siddhi-operator
        siddhi.io/version: 0.2.2
    spec:
      volumes:
        - name: stateful-example-app-1-pvc
          persistentVolumeClaim:
            claimName: stateful-example-app-1-pvc
        - name: stateful-example-app-1-depyml
          configMap:
            name: stateful-example-app-1-depyml
            defaultMode: 420
        - name: stateful-example-app-10
          configMap:
            name: stateful-example-app-10
            defaultMode: 420
      containers:
        - name: siddhi-runner-runtime
          image: 'siddhiio/siddhi-runner-ubuntu:5.1.2'
          command:
            - sh
          args:
            - /home/siddhi_user/siddhi-runner/bin/runner.sh
            - '-Dapps=/home/siddhi_user/siddhi-runner/siddhi-files/ '
            - >-
              -Dconfig=/home/siddhi_user/siddhi-runner/tmp/configs/stateful-example-app-1-depyml
          ports:
            - name: hport
              containerPort: 9090
              protocol: TCP
          env:
            - name: RECEIVER_URL
              value: 'http://0.0.0.0:8080/statefulExample'
          resources: {}
          volumeMounts:
            - name: stateful-example-app-1-pvc
              mountPath: >-
                /home/siddhi_user/siddhi-runner/wso2/runner/siddhi-app-persistence
            - name: stateful-example-app-1-depyml
              mountPath: /home/siddhi_user/siddhi-runner/tmp/configs/
            - name: stateful-example-app-10
              mountPath: /home/siddhi_user/siddhi-runner/siddhi-files/
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 70
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            runAsUser: 802
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-06-03T13:14:05Z'
      lastTransitionTime: '2020-06-03T13:14:05Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-06-03T13:14:05Z'
      lastTransitionTime: '2020-06-03T13:13:49Z'
      reason: NewReplicaSetAvailable
      message: >-
        ReplicaSet "stateful-example-app-1-688ccb49d7" has successfully
        progressed.
